---
- name: Install docker
  community.general.xbps:
    name:
      - docker
      - docker-compose
      - python3-docker
- name: Copy conf
  ansible.builtin.copy:
    src: conf
    dest: /etc/sv/docker/conf
    owner: root
    group: root
    mode: '0644'
- name: Copy daemon.json
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
- name: Enable and start docker
  community.general.runit:
    name: docker
    state: started
    enabled: true
- name: Copy docker.nft
  ansible.builtin.copy:
    src: docker.nft
    dest: /etc/nftables/docker.nft
    owner: root
    group: root
    mode: '0644'
